# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-inspector
  description: '    This component is responsible for provisioning an [AWS Inspector](https://docs'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
